#                                                                        #
# Routes configuration for the Blog package                              #
#                                                                        #
#

-
  name: 'SwiftBox list'
  uriPattern:    ''
  defaults:
    '@package':    'Langeland.SwiftBox'
    '@controller': 'SwiftBox'
    '@action':     'index'
    '@format':     'html'

-
  name: Test actions'
  uriPattern:     'test(/{@action})'
  defaults:
    '@package':    'Langeland.SwiftBox'
    '@controller': 'Test'
#    '@action':     'sendTestMails'
    '@format':     'html'

-
  name: Configuration actions'
  uriPattern:     'configuration(/{@action})'
  defaults:
    '@package':    'Langeland.SwiftBox'
    '@controller': 'Configuration'
    '@action':     'index'
    '@format':     'html'

-
  name: SwiftBox actions'
  uriPattern:     '{@action}(/{@format})'
  defaults:
    '@package':    'Langeland.SwiftBox'
    '@controller': 'SwiftBox'
    '@format':     'html'

-
  name: 'Message actions'
  uriPattern:     '{@action}/{message}(/{@format})'
  defaults:
    '@package':    'Langeland.SwiftBox'
    '@controller': 'SwiftBox'
    '@format':     'html'


